ecommerce:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: gy50980.ap-southeast-7.aws   
      user: AMANPANCHAL2734          
      password: PAnchalAMan3110  
      role: ACCOUNTADMIN       
      database: ECOMMERCE      
      warehouse: COMPUTE_WH    
      schema: dbt              
      threads: 4